# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descri\xe7\xe3o')),
                ('previsto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Previsto')),
                ('atual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Previsto')),
                ('pago', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Pago')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(verbose_name='M\xeas')),
            ],
            options={
                'verbose_name': 'Or\xe7amento',
                'verbose_name_plural': 'Or\xe7amentos',
            },
        ),
        migrations.AddField(
            model_name='conta',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.Orcamento'),
        ),
    ]
