# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='atual',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Atual'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='orcamento.Orcamento'),
        ),
    ]
