# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_auto_20160704_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Valor Atual'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='pago',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Valor Pago'),
        ),
    ]
