# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_auto_20160704_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='situacao',
            field=models.IntegerField(blank=True, choices=[(0, 'Pagar'), (1, 'Pago'), (2, 'Adiar')], default=0, verbose_name='Situa\xe7\xe3o'),
        ),
    ]
