# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0006_auto_20161008_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descri\xe7\xe3o')),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'Principal'), (1, 'Outros')], default=0, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Atual')),
                ('itens', models.IntegerField(blank=True, null=True, verbose_name='Itens')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercados', to='orcamento.Orcamento')),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercado',
            },
        ),
    ]
