# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0007_mercado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descri\xe7\xe3o')),
                ('ordem', models.IntegerField(blank=True, default=999, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Se\xe7\xe3o',
                'verbose_name_plural': 'Se\xe7\xf5es',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['descricao'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ['-ano', '-mes'], 'verbose_name': 'Or\xe7amento', 'verbose_name_plural': 'Or\xe7amentos'},
        ),
    ]
