# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0009_auto_20161105_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercados_old', to='orcamento.Orcamento'),
        ),
    ]
