# Generated by Django 2.0.1 on 2019-05-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0012_auto_20170120_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergiaEletrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh', models.IntegerField(verbose_name='kWh')),
                ('bandeira', models.IntegerField(blank=True, choices=[(0, 'Verde'), (1, 'Amarela'), (2, 'Vermelha 1'), (3, 'Vermelha 2')], default=0, verbose_name='Bandeira')),
                ('valor_kwh', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor kWh')),
                ('outros_custos', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Outros Custos')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energia_eletrica', to='orcamento.Orcamento')),
            ],
            options={
                'verbose_name': 'Consumo de Energia Elétrica',
                'verbose_name_plural': 'Consumos de Energia Elétrica',
                'ordering': ('orcamento',),
            },
        ),
    ]
