# Generated by Django 2.0.1 on 2019-05-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0013_energiaeletrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energiaeletrica',
            name='valor_kwh',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Valor kWh'),
        ),
    ]
