# Generated by Django 2.2.4 on 2019-08-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0014_auto_20190511_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='recorrente',
            field=models.BooleanField(blank=True, default=False, verbose_name='Recorrente'),
        ),
    ]
