# Generated by Django 2.2.10 on 2020-02-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0015_auto_20190814_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=3, verbose_name='Sigla')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
                'ordering': ['nome'],
            },
        ),
    ]
