# Generated by Django 5.0.8 on 2025-04-16 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0016_moeda'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default', to='orcamento.orcamento')),
            ],
            options={
                'verbose_name': 'Orcamento Default',
                'verbose_name_plural': 'Orcamento Default',
                'ordering': ['-orcamento'],
            },
        ),
    ]
