language: python
env:
  - SECRET=")vjn2yf9+7l&llpv3_ieqyoz^w)f02$h%$hja%em7^1+yhbl&z"
  - DATABASE_URL="sqlite://db.sqlite"
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script: make test
after_success:
  - coveralls
