# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamento', '0012_auto_20170120_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Bandeira',
                'verbose_name_plural': 'Bandeira',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('limite', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor em Dolar')),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='cartao.Bandeira')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.CreateModel(
            name='CompraCartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('valor_real', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor em Real')),
                ('valor_dolar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor em Dolar')),
                ('valor_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Valor Atual')),
                ('valor_fatura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Atual')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Atual')),
                ('parcelas', models.IntegerField(blank=True, default=1, verbose_name='Parcelas')),
                ('parcela_atual', models.IntegerField(blank=True, default=1, verbose_name='Parcela')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_cartao', to='orcamento.Categoria')),
            ],
            options={
                'verbose_name': 'Compra Cartão',
                'verbose_name_plural': 'Compras Cartão',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='cartao.Cartao')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='orcamento.Orcamento')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
            },
        ),
        migrations.AddField(
            model_name='compracartao',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='cartao.Fatura'),
        ),
    ]
