# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracartao',
            name='descricao_fatura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição Fatura'),
        ),
        migrations.AlterField(
            model_name='compracartao',
            name='descricao',
            field=models.CharField(default='', max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compracartao',
            name='valor_fatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Fatura'),
        ),
        migrations.AlterField(
            model_name='compracartao',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Final'),
        ),
        migrations.AlterField(
            model_name='compracartao',
            name='valor_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Valor Inicial'),
        ),
    ]
