# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0002_auto_20170313_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='aberta',
            field=models.BooleanField(default=True, verbose_name='Aberta'),
        ),
    ]
