# Generated by Django 2.0.1 on 2018-06-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0004_fatura_valor_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracartao',
            name='valor_parcela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Parcela'),
        ),
    ]
