# Generated by Django 2.0.1 on 2018-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0005_compracartao_valor_parcela'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'SMS Cartão',
                'verbose_name_plural': 'SMSs Cartão',
            },
        ),
    ]
