# Generated by Django 2.0.1 on 2018-08-27 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0006_smscartao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smscartao',
            options={'ordering': ['criado'], 'verbose_name': 'SMS Cartão', 'verbose_name_plural': 'SMSs Cartão'},
        ),
        migrations.AddField(
            model_name='smscartao',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
