# Generated by Django 2.0.1 on 2018-08-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0007_auto_20180827_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoAliasSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='cartao.Cartao')),
            ],
        ),
    ]
