# Generated by Django 2.2.4 on 2019-08-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0008_cartaoaliassms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compracartao',
            name='recorrente',
            field=models.BooleanField(blank=True, default=False, verbose_name='Recorrente'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='aberta',
            field=models.BooleanField(blank=True, default=True, verbose_name='Aberta'),
        ),
    ]
