# Generated by Django 2.2.4 on 2019-10-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0009_auto_20190814_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compracartao',
            options={'ordering': ('-id',), 'verbose_name': 'Compra Cartão', 'verbose_name_plural': 'Compras Cartão'},
        ),
    ]
