# Generated by Django 2.2.10 on 2020-02-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0010_auto_20191017_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatura',
            options={'ordering': ['-orcamento', 'cartao'], 'verbose_name': 'Fatura', 'verbose_name_plural': 'Faturas'},
        ),
    ]
