# Generated by Django 2.2.18 on 2021-04-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0012_auto_20200223_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='limite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Limite'),
        ),
    ]
