# Generated by Django 2.2.20 on 2021-05-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0013_auto_20210401_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'ordering': ['ordem'], 'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AddField(
            model_name='cartao',
            name='ordem',
            field=models.IntegerField(blank=True, default=1, verbose_name='Ordem'),
        ),
    ]
