# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamento', '0010_auto_20161105_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descri\xe7\xe3o')),
                ('quantidade_sugerida', models.IntegerField(blank=True, default=1, verbose_name='Qtd Sugerida')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descri\xe7\xe3o')),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'Principal'), (1, 'Outros')], default=0, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Atual')),
                ('itens', models.IntegerField(blank=True, null=True, verbose_name='Itens')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercados', to='orcamento.Orcamento')),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercado',
            },
        ),
        migrations.CreateModel(
            name='SecaoLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descri\xe7\xe3o')),
                ('ordem', models.IntegerField(blank=True, default=999, verbose_name='Ordem')),
            ],
            options={
                'ordering': ('ordem', 'descricao'),
                'verbose_name': 'Se\xe7\xe3o',
                'verbose_name_plural': 'Se\xe7\xf5es',
            },
        ),
        migrations.AddField(
            model_name='itenslista',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.SecaoLista'),
        ),
    ]
