# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenslista',
            name='unidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade'),
        ),
    ]
