# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_itenslista_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenslista',
            name='unidade',
            field=models.CharField(blank=True, default='UN', max_length=20, verbose_name='Unidade'),
        ),
    ]
