# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20161105_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='comprar',
            field=models.BooleanField(default=True),
        ),
    ]
