# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20161105_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenslista',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
