# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_auto_20161105_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='quantidade_sugerida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtd Sugerida'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='unidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade'),
        ),
    ]
