# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20161105_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcompra',
            options={'ordering': ('lista', 'item')},
        ),
    ]
