# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_auto_20161106_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mercado',
            options={'ordering': ('-orcamento', 'tipo'), 'verbose_name': 'Mercado', 'verbose_name_plural': 'Mercado'},
        ),
    ]
