# Generated by Django 2.2.10 on 2020-02-23 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0010_auto_20191017_0135'),
        ('orcamento', '0016_moeda'),
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoViagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('valor_real', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor em Reais')),
                ('valor_dolar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor em Dólares')),
                ('valor_moeda', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor na moeda local')),
                ('taxa_conversao', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Taxa de conversão')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_viagem', to='orcamento.Categoria')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_viagem', to='cartao.Fatura')),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_viagem', to='orcamento.Moeda')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='viagem.Viagem')),
            ],
            options={
                'verbose_name': 'Gasto Viagem',
                'verbose_name_plural': 'Gastos de Viagem',
                'ordering': ['dia', 'id'],
            },
        ),
    ]
