# Generated by Django 2.2.10 on 2020-02-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0002_gastoviagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='orcamento.Orcamento'),
        ),
    ]
